version: '3.8'
services:
  php:
    build: .
    container_name: lab6_php
    volumes:
      - ./code:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: lab6_redis
    ports:
      - "6379:6379"

volumes:
  redis_data:
  ch_data:
